name: Deploy production version of the Website

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  Build-And-Deploy-Preview:
    if: ${{ github.repository_owner == 'opensciencegrid.github.io' }}
    runs-on: ubuntu-18.04
    env:
      CNAME: opensciencegrid.org
    steps:
      - uses: actions/checkout@v2

      - name: Initialize GH User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build and Deploy
        run: |
          # Build the production version of website
          JEKYLL_ENV=production bundle exec jekyll build

          # Add in the appropriate CNAME file
          echo "${{ env.CNAME }}" > _site/CNAME

          # Commit the build then use 'git subtree' to create a branch with just the _site contents
          git add _site -f
          git commit -m "Build Production Website"
          git checkout -b split-branch `git subtree split --prefix temp-dir production`

          # Push to Production
          git push ${{ env.production_url }} HEAD:gh-pages --force
